import { config } from "@fortawesome/fontawesome-svg-core";
import {
  faFacebook,
  faGoogle,
  faInstagram,
  faTiktok,
} from "@fortawesome/free-brands-svg-icons";
import {
  faArrowRightFromBracket,
  faArrowRight,
  faArrowRotateRight,
  faArrowUpRightFromSquare,
  faBarsStaggered,
  faBell,
  faCameraRetro,
  faCheck,
  faEye,
  faEyeSlash,
  faChartColumn,
  faChevronDown,
  faChevronRight,
  faCircleNodes,
  faClockRotateLeft,
  faFolderTree,
  faMagnifyingGlass,
  faFilm,
  faHouse,
  faLayerGroup,
  faLock,
  faPalette,
  faPenNib,
  faPlus,
  faRectangleList,
  faRotateLeft,
  faSearch,
  faShieldHalved,
  faSpinner,
  faThumbtack,
  faTrashCan,
  faUserGear,
  faUserPen,
  faUserLarge,
  faUserPlus,
  faUserGroup,
  faWandMagicSparkles,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

export {
  faFacebook,
  faGoogle,
  faInstagram,
  faTiktok,
  faArrowRightFromBracket,
  faArrowRight,
  faArrowRotateRight,
  faArrowUpRightFromSquare,
  faBarsStaggered,
  faBell,
  faCameraRetro,
  faCheck,
  faEye,
  faEyeSlash,
  faChartColumn,
  faChevronDown,
  faChevronRight,
  faCircleNodes,
  faClockRotateLeft,
  faFolderTree,
  faMagnifyingGlass,
  faFilm,
  faHouse,
  faLayerGroup,
  faLock,
  faPalette,
  faPenNib,
  faPlus,
  faRectangleList,
  faRotateLeft,
  faSearch,
  faShieldHalved,
  faSpinner,
  faThumbtack,
  faTrashCan,
  faUserGear,
  faUserPen,
  faUserLarge,
  faUserPlus,
  faUserGroup,
  faWandMagicSparkles,
  faXmark,
};
