import { config } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faArrowUpRightFromSquare,
  faBarsStaggered,
  faBell,
  faCameraRetro,
  faChartColumn,
  faChevronRight,
  faCircleNodes,
  faClockRotateLeft,
  faFolderTree,
  faFilm,
  faHouse,
  faLayerGroup,
  faLock,
  faPalette,
  faRectangleList,
  faSearch,
  faShieldHalved,
  faUserLarge,
  faUserPlus,
  faUserGroup,
  faWandMagicSparkles,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

export {
  faArrowRight,
  faArrowUpRightFromSquare,
  faBarsStaggered,
  faBell,
  faCameraRetro,
  faChartColumn,
  faChevronRight,
  faCircleNodes,
  faClockRotateLeft,
  faFolderTree,
  faFilm,
  faHouse,
  faLayerGroup,
  faLock,
  faPalette,
  faRectangleList,
  faSearch,
  faShieldHalved,
  faUserLarge,
  faUserPlus,
  faUserGroup,
  faWandMagicSparkles,
};
